### ISSUE TITLE
paper_authors are inconsistent/wrong

### ISSUE THREAD

**Issue by hughjonesd** [unjournal/unjournaldata#23]
Some authors in `paper_authors` are "First Last", some are "Last, First" and some are "First, Last" which is wrong. (Examples: "Matt, Boyd", "Isabel, Johnson" .)

Some are "Jones, David", some are "Jones, D" and some are "Jones, D.".

 There's also "Glomseth" which looks odd.

Most important is to fix the "First, Last" items and to keep them consistent w.r.t last/first order.

**Comment by davitUJ** [comment]
I think Will has been adding authors here - this should be mostly in "First Last" order now, but it's still in progress

**Comment by davitUJ** [comment]
For all papers added, the names have been formatted in the same format now ' first name last name'

**Comment by hughjonesd** [comment]
Okay, close if fixed
